package entities;

public enum ThiefState {
    PLANNING_THE_HEIST,
    DECIDING_WHAT_TO_DO,
    ASSEMBLING_A_GROUP,
    WAITING_FOR_GROUP_ARRIVAL,
    PRESENTING_THE_REPORT,

    CONCENTRATION_SITE,
    CRAWLING_INWARDS,
    AT_A_ROOM,
    CRAWLING_OUTWARDS,
    COLLECTION_SITE
}
